import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackToTop from "./components/BackToTop";
import Footer from "./components/Footer";
import { LightboxProvider } from "./components/LightboxProvider";
import Navbar from "./components/Navbar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				{/* GoatCounter analytics — tracks unique visitors, no cookies */}
				{process.env.NEXT_PUBLIC_GOATCOUNTER_CODE && (
					<script
						async
						data-goatcounter={`https://${process.env.NEXT_PUBLIC_GOATCOUNTER_CODE}.goatcounter.com/count`}
						src="https://gc.zgo.at/count.js"
					/>
				)}
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<LightboxProvider>
					<Navbar />
					{children}
					<Footer />
					<BackToTop />
				</LightboxProvider>
			</body>
		</html>
	);
}
